#!/usr/bin/env python

import yaml

file = open("finfish_freshwater.yml", 'r')
dataset = yaml.load(file)

for project in dataset:
    print(project["title"])
    for person in project["project_lead"]:
        print(person["org"])
    for person in project["project_team"]:
        print(person["org"])
    for person in project["collaborators"]:
        print(person["org"])
