#!/usr/bin/env python

"""
Usage: make_edges <file>

Options:
    -h, --help    Show usage info.
"""

from docopt import docopt
import yaml

if __name__ == '__main__':
    arguments = docopt(__doc__, version='0.1')

file = open(arguments["<file>"], 'r')
dataset = yaml.load(file)
for project in dataset:
    print(project["title"])
    for person in project["project_lead"]:
        print(person["org"])
    for person in project["project_team"]:
        print(person["org"])
    for person in project["collaborators"]:
        print(person["org"])

file.close()
