#!/usr/bin/env python

"""
Usage: make_edges_org <file>

Options:
    -h, --help    Show usage info.
"""

from docopt import docopt
import yaml
import csv
import itertools

if __name__ == '__main__':
    arguments = docopt(__doc__, version='0.1')

filename = arguments["<file>"]
file = open(filename, 'r')
dataset = yaml.load(file)

filename_without_extension = filename.split(".")[0]
csvfile = open("{}_org_edges.csv".format(filename_without_extension), "w")
csv_output = csv.writer(csvfile, delimiter = ",")
csv_output.writerow(["SOURCE", "TARGET", "TYPE"])

def clean_up():
    global file
    file.close()
    global csvfile
    csvfile.close()

def extract_people(project):
    return project["project_lead"] + project["project_team"] + project["collaborators"]

def extract_organizations(people):
    # we are removing duplicate org names
    # by converting the list to a set
    return set([person["org"] for person in people])

for project in dataset:
    all_the_people = extract_people(project)
    organizations = extract_organizations(all_the_people)
    edges = itertools.combinations(organizations, 2)
    for edge in edges:
        edge_list = list(edge)
        edge_list.append("undirected")
        edge_list.append(project["title"].title())
        csv_output.writerow(edge_list)

clean_up()
